name: Run bot
on:
  push:
  pull_request:
  schedule:
  - cron: '* * * * *'  # every five minutes

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Every time
      run: echo "$TWITTER_CONSUMER_KEY : $TWITTER_ACCESS_TOKEN"
      env:
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
