name: Run bot
on:
  push:
  pull_request:
  schedule:
    - cron: '* * * * *'  # every five minutes
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "hello"
