name: Run bot
on:
  push:
  pull_request:
  schedule:
  - cron: '* * * * *'  # every minute

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pip install
    - name: Every time
      run: echo "$TWITTER_CONSUMER_KEY , $TWITTER_ACCESS_TOKEN"
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
